services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: ev_api
    ports:
      - "8000:8000"
    restart: always
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/')"]
      interval: 10s
      timeout: 5s
      retries: 5

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: ev_streamlit
    ports:
      - "8501:8501"
    depends_on:
      api:
        condition: service_healthy
    restart: always